apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab5-webapp
spec:
  selector:
    matchLabels:
      app: lab5-webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: lab5-webapp
    spec:
      containers:
        - name: lab5-webapp
          image: docker.io/mendasium/tpp-lab5
          ports:
            - containerPort: 5000
              name: "http"
          env:
            - name: ProcessingPath
              value: http://$(LAB5_S_SERVICE_SERVICE_HOST):5000
              # value: lab5-s-service.default.svc.cluster.local:5000
          resources:
            limits:
              memory: 2Gi
              cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: lab5-service
spec:
  selector:
    app: lab5-webapp
  ports:
    - name: "http"
      protocol: TCP
      port: 5000
      # targetPort: 5000
      nodePort: 30103
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab5-s-webapp
spec:
  selector:
    matchLabels:
      app: lab5-s-webapp
  replicas: 4
  template:
    metadata:
      labels:
        app: lab5-s-webapp
    spec:
      containers:
        - name: lab5-s-webapp
          image: docker.io/mendasium/tpp-lab5
          ports:
            - containerPort: 5000
              name: "http"
          resources:
            limits:
              memory: 1Gi
              cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: lab5-s-service
spec:
  selector:
    app: lab5-s-webapp
  ports:
    - name: "http"
      protocol: TCP
      port: 5000
      # targetPort: 5000
      nodePort: 30104
  type: NodePort



# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: lab5-service-webapp
# spec:
#   selector:
#     matchLabels:
#       app: lab5-service-webapp
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: lab5-service-webapp
#     spec:
#       containers:
#         - name: lab5-service-webapp
#           image: docker.io/mendasium/tpp-lab5-service
#           ports:
#             - containerPort: 5000
#               name: "http"
#           resources:
#             limits:
#               memory: 2Gi
#               cpu: "1"

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: lab5-s-service
# spec:
#   selector:
#     app: lab5-service-webapp
#   ports:
#     - name: "http"
#       protocol: TCP
#       port: 5000
#       # targetPort: 5000
#       nodePort: 30104
#   type: NodePort
